tessdata.path=./config
google.application.credentials=${GOOGLE_APPLICATION_CREDENTIALS:my-receipt-api-65cf36b6482b.json}
google.documentai.project-id=${GOOGLE_PROJECT_ID:}
google.documentai.location=${GOOGLE_DOCUMENT_AI_LOCATION:us}
google.documentai.processor-id=${GOOGLE_DOCUMENT_AI_PROCESSOR_ID:}
